"""
CI/CD Pipeline Generator — Sprint 94
Generates GitHub Actions and Azure DevOps pipeline definitions.

Usage:
    python cicd_generator.py                          # Generate both
    python cicd_generator.py --format github          # GitHub Actions only
    python cicd_generator.py --format azdo             # Azure DevOps only
"""

import argparse
import json
import logging
import os
from datetime import datetime, timezone
from pathlib import Path

logger = logging.getLogger(__name__)

WORKSPACE = Path(__file__).resolve().parent
OUTPUT_DIR = WORKSPACE / "output" / "cicd"


def _load_config(config_path=None):
    """Load migration.yaml config."""
    if config_path:
        p = Path(config_path)
    else:
        p = WORKSPACE / "migration.yaml"
    if not p.exists():
        return {}
    try:
        import yaml
        with open(p, encoding="utf-8") as f:
            return yaml.safe_load(f) or {}
    except ImportError:
        return {}


# ─────────────────────────────────────────────
#  Secret Mapping
# ─────────────────────────────────────────────

def extract_secrets(config):
    """Extract required secrets from config for CI/CD secret injection.

    Returns:
        list of dicts with name, description, env_var, and source metadata.
    """
    secrets = []
    target = config.get("target", "fabric")

    # Common secrets
    secrets.append({
        "name": "AZURE_CREDENTIALS",
        "description": "Azure service principal credentials (JSON)",
        "env_var": "AZURE_CREDENTIALS",
        "required": True,
    })

    if target in ("fabric", "all"):
        secrets.append({
            "name": "FABRIC_WORKSPACE_ID",
            "description": "Microsoft Fabric workspace GUID",
            "env_var": "FABRIC_WORKSPACE_ID",
            "required": True,
        })
        secrets.append({
            "name": "FABRIC_TOKEN",
            "description": "Fabric API bearer token",
            "env_var": "FABRIC_TOKEN",
            "required": True,
        })

    if target in ("databricks", "dbt", "pyspark", "auto", "all"):
        secrets.append({
            "name": "DATABRICKS_HOST",
            "description": "Databricks workspace URL",
            "env_var": "DATABRICKS_HOST",
            "required": True,
        })
        secrets.append({
            "name": "DATABRICKS_TOKEN",
            "description": "Databricks personal access token",
            "env_var": "DATABRICKS_TOKEN",
            "required": True,
        })
        catalog = config.get("databricks", {}).get("catalog", "main")
        secrets.append({
            "name": "DATABRICKS_CATALOG",
            "description": f"Unity Catalog name (default: {catalog})",
            "env_var": "INFORMATICA_DATABRICKS_CATALOG",
            "required": False,
        })

    return secrets


# ─────────────────────────────────────────────
#  GitHub Actions
# ─────────────────────────────────────────────

def generate_github_actions(config, output_dir=None):
    """Generate .github/workflows/migration.yml.

    Returns:
        str: YAML content for the GitHub Actions workflow.
    """
    target = config.get("target", "fabric")
    secrets = extract_secrets(config)

    # Build secret references
    secret_env_lines = []
    for s in secrets:
        secret_env_lines.append(f"          {s['env_var']}: ${{{{ secrets.{s['name']} }}}}")
    secret_env_block = "\n".join(secret_env_lines)

    deploy_step = ""
    if target in ("fabric", "all"):
        deploy_step = """\
      - name: Deploy to Fabric
        if: github.ref == 'refs/heads/main'
        env:
          FABRIC_WORKSPACE_ID: ${{ secrets.FABRIC_WORKSPACE_ID }}
          FABRIC_TOKEN: ${{ secrets.FABRIC_TOKEN }}
        run: python deploy_to_fabric.py --dry-run"""
    else:
        deploy_step = """\
      - name: Deploy to Databricks
        if: github.ref == 'refs/heads/main'
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: python deploy_to_databricks.py --dry-run"""

    workflow = f"""\
# Auto-generated by cicd_generator.py — Sprint 94
# Generated: {datetime.now(timezone.utc).isoformat()}
#
# Informatica → {'Fabric' if target == 'fabric' else 'Databricks'} Migration Pipeline
# Stages: Assess → Convert → Validate → Deploy

name: Migration Pipeline

on:
  push:
    branches: [main, develop]
    paths:
      - 'input/**'
      - 'migration.yaml'
      - 'run_*.py'
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      target:
        description: 'Target platform'
        required: false
        default: '{target}'
        type: choice
        options:
          - fabric
          - databricks
          - dbt
          - auto
      dry_run:
        description: 'Dry run (no deployment)'
        required: false
        default: true
        type: boolean

permissions:
  contents: read
  id-token: write

env:
  PYTHON_VERSION: '3.12'
  INFORMATICA_MIGRATION_TARGET: ${{{{ github.event.inputs.target || '{target}' }}}}

jobs:
  assess:
    name: "\U0001F50D Assessment"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{{{ env.PYTHON_VERSION }}}}
          cache: pip

      - name: Install dependencies
        run: pip install -e ".[all]"

      - name: Run assessment
        run: python run_assessment.py

      - name: Upload inventory
        uses: actions/upload-artifact@v4
        with:
          name: inventory
          path: output/inventory/

  convert:
    name: "\u2699\uFE0F Conversion"
    needs: assess
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{{{ env.PYTHON_VERSION }}}}
          cache: pip

      - name: Install dependencies
        run: pip install -e ".[all]"

      - name: Download inventory
        uses: actions/download-artifact@v4
        with:
          name: inventory
          path: output/inventory/

      - name: Convert SQL
        run: python run_sql_migration.py

      - name: Generate notebooks
        run: python run_notebook_migration.py

      - name: Generate pipelines
        run: python run_pipeline_migration.py

      - name: Generate schema
        run: python run_schema_generator.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: migration-output
          path: |
            output/sql/
            output/notebooks/
            output/pipelines/
            output/schema/

  validate:
    name: "\u2705 Validation"
    needs: convert
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{{{ env.PYTHON_VERSION }}}}
          cache: pip

      - name: Install dependencies
        run: pip install -e ".[all]"

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: migration-output
          path: output/

      - name: Download inventory
        uses: actions/download-artifact@v4
        with:
          name: inventory
          path: output/inventory/

      - name: Run validation
        run: python run_validation.py

      - name: Run artifact validation
        run: python run_artifact_validation.py

      - name: Run tests
        run: pytest tests/ -x --tb=short

      - name: Upload validation results
        uses: actions/upload-artifact@v4
        with:
          name: validation
          path: output/validation/

  deploy:
    name: "\U0001F680 Deploy"
    needs: validate
    if: github.ref == 'refs/heads/main' && github.event.inputs.dry_run != 'true'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{{{ env.PYTHON_VERSION }}}}
          cache: pip

      - name: Install dependencies
        run: pip install -e ".[all]"

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          name: migration-output
          path: output/

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{{{ secrets.AZURE_CREDENTIALS }}}}

      {deploy_step}

      - name: Upload deployment log
        uses: actions/upload-artifact@v4
        with:
          name: deployment-log
          path: output/deployment_log.json
"""

    if output_dir:
        out = Path(output_dir)
    else:
        out = OUTPUT_DIR
    gh_dir = out / "github"
    gh_dir.mkdir(parents=True, exist_ok=True)
    path = gh_dir / "migration.yml"
    path.write_text(workflow, encoding="utf-8")
    return workflow, str(path)


# ─────────────────────────────────────────────
#  Azure DevOps
# ─────────────────────────────────────────────

def generate_azure_devops(config, output_dir=None):
    """Generate azure-pipelines.yml.

    Returns:
        str: YAML content for the Azure DevOps pipeline.
    """
    target = config.get("target", "fabric")

    deploy_task = ""
    if target in ("fabric", "all"):
        deploy_task = """\
          - script: python deploy_to_fabric.py
            displayName: 'Deploy to Fabric'
            env:
              FABRIC_WORKSPACE_ID: $(FABRIC_WORKSPACE_ID)
              FABRIC_TOKEN: $(FABRIC_TOKEN)"""
    else:
        deploy_task = """\
          - script: python deploy_to_databricks.py
            displayName: 'Deploy to Databricks'
            env:
              DATABRICKS_HOST: $(DATABRICKS_HOST)
              DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)"""

    pipeline = f"""\
# Auto-generated by cicd_generator.py — Sprint 94
# Generated: {datetime.now(timezone.utc).isoformat()}
#
# Informatica → {'Fabric' if target == 'fabric' else 'Databricks'} Migration Pipeline
# Stages: Assess → Convert → Validate → Deploy

trigger:
  branches:
    include:
      - main
      - develop
  paths:
    include:
      - input/*
      - migration.yaml
      - run_*.py

pr:
  branches:
    include:
      - main

variables:
  pythonVersion: '3.12'
  INFORMATICA_MIGRATION_TARGET: '{target}'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Assess
    displayName: 'Assessment'
    jobs:
      - job: Assessment
        displayName: 'Parse & Inventory'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'

          - script: pip install -e ".[all]"
            displayName: 'Install dependencies'

          - script: python run_assessment.py
            displayName: 'Run assessment'

          - publish: output/inventory/
            artifact: inventory
            displayName: 'Publish inventory'

  - stage: Convert
    displayName: 'Conversion'
    dependsOn: Assess
    jobs:
      - job: Conversion
        displayName: 'Convert Mappings & Workflows'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'

          - script: pip install -e ".[all]"
            displayName: 'Install dependencies'

          - download: current
            artifact: inventory
            patterns: '**/*'

          - script: |
              mkdir -p output/inventory
              cp -r $(Pipeline.Workspace)/inventory/* output/inventory/
            displayName: 'Restore inventory'

          - script: python run_sql_migration.py
            displayName: 'Convert SQL'

          - script: python run_notebook_migration.py
            displayName: 'Generate notebooks'

          - script: python run_pipeline_migration.py
            displayName: 'Generate pipelines'

          - script: python run_schema_generator.py
            displayName: 'Generate schema'

          - publish: output/
            artifact: migration-output
            displayName: 'Publish migration output'

  - stage: Validate
    displayName: 'Validation'
    dependsOn: Convert
    jobs:
      - job: Validation
        displayName: 'Run Tests & Validation'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'

          - script: pip install -e ".[all]"
            displayName: 'Install dependencies'

          - download: current
            artifact: migration-output
            patterns: '**/*'

          - script: |
              cp -r $(Pipeline.Workspace)/migration-output/* output/
            displayName: 'Restore migration output'

          - script: python run_validation.py
            displayName: 'Run validation'

          - script: python run_artifact_validation.py
            displayName: 'Validate artifacts'

          - script: pytest tests/ -x --tb=short --junitxml=output/test-results.xml
            displayName: 'Run tests'

          - task: PublishTestResults@2
            inputs:
              testResultsFiles: 'output/test-results.xml'
              testRunTitle: 'Migration Tests'
            condition: always()

  - stage: Deploy_Dev
    displayName: 'Deploy (Dev)'
    dependsOn: Validate
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
    jobs:
      - deployment: DeployDev
        displayName: 'Deploy to Dev'
        environment: development
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: UsePythonVersion@0
                  inputs:
                    versionSpec: '$(pythonVersion)'
                - script: pip install -e ".[all]"
                  displayName: 'Install dependencies'
                - download: current
                  artifact: migration-output
                - script: |
                    cp -r $(Pipeline.Workspace)/migration-output/* output/
                  displayName: 'Restore output'
{deploy_task}

  - stage: Deploy_Prod
    displayName: 'Deploy (Production)'
    dependsOn: Validate
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - deployment: DeployProd
        displayName: 'Deploy to Production'
        environment: production
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: UsePythonVersion@0
                  inputs:
                    versionSpec: '$(pythonVersion)'
                - script: pip install -e ".[all]"
                  displayName: 'Install dependencies'
                - download: current
                  artifact: migration-output
                - script: |
                    cp -r $(Pipeline.Workspace)/migration-output/* output/
                  displayName: 'Restore output'
{deploy_task}
"""

    if output_dir:
        out = Path(output_dir)
    else:
        out = OUTPUT_DIR
    azdo_dir = out / "azdo"
    azdo_dir.mkdir(parents=True, exist_ok=True)
    path = azdo_dir / "azure-pipelines.yml"
    path.write_text(pipeline, encoding="utf-8")
    return pipeline, str(path)


# ─────────────────────────────────────────────
#  Pipeline Validation
# ─────────────────────────────────────────────

def validate_github_actions(content):
    """Validate GitHub Actions YAML structure. Returns (valid, issues)."""
    issues = []

    # Check required top-level keys
    for key in ["name:", "on:", "jobs:"]:
        if key not in content:
            issues.append(f"Missing required key: {key}")

    # Check for hardcoded secrets (security check)
    import re
    if re.search(r'(password|token|secret|key)\s*[:=]\s*["\'][^${}]+["\']', content, re.IGNORECASE):
        issues.append("Potential hardcoded secret detected")

    # Check stages exist
    for stage in ["assess:", "convert:", "validate:", "deploy:"]:
        if stage not in content:
            issues.append(f"Missing stage: {stage}")

    return len(issues) == 0, issues


def validate_azure_devops(content):
    """Validate Azure DevOps pipeline YAML structure. Returns (valid, issues)."""
    issues = []

    for key in ["trigger:", "stages:"]:
        if key not in content:
            issues.append(f"Missing required key: {key}")

    # Check for hardcoded secrets
    import re
    if re.search(r'(password|token|secret|key)\s*[:=]\s*["\'][^${}]+["\']', content, re.IGNORECASE):
        issues.append("Potential hardcoded secret detected")

    return len(issues) == 0, issues


# ─────────────────────────────────────────────
#  Orchestrator
# ─────────────────────────────────────────────

def generate_cicd(config=None, fmt=None, output_dir=None):
    """Generate all CI/CD pipeline definitions.

    Args:
        config: Migration config dict.
        fmt: Output format (github/azdo/all).
        output_dir: Output base directory.

    Returns:
        dict with generated file paths and validation results.
    """
    config = config or _load_config()
    fmt = fmt or "all"
    result = {"github": None, "azdo": None, "secrets": [], "validation": {}}

    result["secrets"] = extract_secrets(config)

    if fmt in ("github", "all"):
        content, path = generate_github_actions(config, output_dir)
        valid, issues = validate_github_actions(content)
        result["github"] = path
        result["validation"]["github"] = {"valid": valid, "issues": issues}

    if fmt in ("azdo", "all"):
        content, path = generate_azure_devops(config, output_dir)
        valid, issues = validate_azure_devops(content)
        result["azdo"] = path
        result["validation"]["azdo"] = {"valid": valid, "issues": issues}

    return result


def main():
    parser = argparse.ArgumentParser(description="CI/CD Pipeline Generator")
    parser.add_argument("--format", choices=["github", "azdo", "all"], default="all")
    parser.add_argument("--config", type=str, default=None)
    parser.add_argument("--output-dir", type=str, default=None)
    args = parser.parse_args()

    config = _load_config(args.config)
    result = generate_cicd(config=config, fmt=args.format, output_dir=args.output_dir)

    print(f"\n  CI/CD Pipeline Generation Complete")
    print(f"  ──────────────────────────────────")
    if result["github"]:
        v = result["validation"].get("github", {})
        status = "valid" if v.get("valid") else f"issues: {v.get('issues', [])}"
        print(f"  GitHub Actions: {result['github']} ({status})")
    if result["azdo"]:
        v = result["validation"].get("azdo", {})
        status = "valid" if v.get("valid") else f"issues: {v.get('issues', [])}"
        print(f"  Azure DevOps:   {result['azdo']} ({status})")
    print(f"  Secrets required: {len(result['secrets'])}")
    for s in result["secrets"]:
        req = " (required)" if s.get("required") else ""
        print(f"    → {s['name']}: {s['description']}{req}")
    print()


if __name__ == "__main__":
    main()
