# Auto-generated by Sprint 93 — Container & Kubernetes Deployment
# Multi-stage build for informatica-to-fabric migration tool

FROM python:3.12-slim AS base

# Security: non-root user
RUN groupadd --gid 1000 migrator && \
    useradd --uid 1000 --gid migrator --shell /bin/bash --create-home migrator

WORKDIR /app

# Install dependencies first (cache layer)
COPY requirements.txt pyproject.toml ./
RUN pip install --no-cache-dir -e ".[all]" 2>/dev/null || pip install --no-cache-dir pyyaml pytest

# Copy application code
COPY run_*.py deploy_*.py generate_*.py dashboard.py plugins.py sdk.py api_server.py \
     rule_engine.py catalog_integration.py datadog_integration.py agentic_alerting.py \
     monitoring_platform.py idmc_client.py migration_review.py iac_generator.py \
     cicd_generator.py migration.yaml ./

COPY templates/ templates/
COPY input/ input/

# Create output directory
RUN mkdir -p output && chown -R migrator:migrator /app

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \
    CMD python -c "import api_server; print(api_server.api_health())" || exit 1

USER migrator

# Default: run the API server
EXPOSE 8000
CMD ["python", "api_server.py"]
