-- ============================================================
-- Stored Procedure: SP_CALC_RANKINGS
-- Source DB: Oracle
-- Purpose: Calculate customer and product rankings using analytics
-- Tests: Oracle analytic functions (LEAD, LAG, DENSE_RANK, etc.)
-- ============================================================

CREATE OR REPLACE PROCEDURE SALES.SP_CALC_RANKINGS
IS
    v_run_date DATE := SYSDATE;
BEGIN
    -- Step 1: Customer rankings with analytic functions
    MERGE INTO SALES.CUSTOMER_RANKINGS tgt
    USING (
        SELECT
            CUSTOMER_ID,
            TOTAL_REVENUE,
            DENSE_RANK() OVER (ORDER BY TOTAL_REVENUE DESC) AS REVENUE_RANK,
            NTILE(4) OVER (ORDER BY TOTAL_REVENUE DESC) AS QUARTILE,
            ROW_NUMBER() OVER (ORDER BY TOTAL_REVENUE DESC) AS ROW_NUM,
            FIRST_VALUE(CUSTOMER_ID) OVER (
                ORDER BY TOTAL_REVENUE DESC
                ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
            ) AS TOP_CUSTOMER,
            LAST_VALUE(CUSTOMER_ID) OVER (
                ORDER BY TOTAL_REVENUE DESC
                ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
            ) AS BOTTOM_CUSTOMER,
            LAG(TOTAL_REVENUE, 1, 0) OVER (ORDER BY TOTAL_REVENUE DESC) AS PREV_REVENUE,
            LEAD(TOTAL_REVENUE, 1, 0) OVER (ORDER BY TOTAL_REVENUE DESC) AS NEXT_REVENUE,
            TOTAL_REVENUE - LAG(TOTAL_REVENUE, 1, 0) OVER (ORDER BY TOTAL_REVENUE DESC) AS REVENUE_GAP
        FROM (
            SELECT
                CUSTOMER_ID,
                NVL(SUM(QUANTITY * UNIT_PRICE), 0) AS TOTAL_REVENUE
            FROM SALES.ORDERS
            WHERE ORDER_STATUS != 'CANCELLED'
              AND ORDER_DATE >= ADD_MONTHS(v_run_date, -12)
            GROUP BY CUSTOMER_ID
        )
    ) src
    ON (tgt.CUSTOMER_ID = src.CUSTOMER_ID)
    WHEN MATCHED THEN UPDATE SET
        tgt.REVENUE_RANK   = src.REVENUE_RANK,
        tgt.QUARTILE        = src.QUARTILE,
        tgt.TOTAL_REVENUE   = src.TOTAL_REVENUE,
        tgt.PREV_REVENUE    = src.PREV_REVENUE,
        tgt.NEXT_REVENUE    = src.NEXT_REVENUE,
        tgt.REVENUE_GAP     = src.REVENUE_GAP,
        tgt.LAST_CALCULATED = SYSDATE
    WHEN NOT MATCHED THEN INSERT (
        CUSTOMER_ID, REVENUE_RANK, QUARTILE, TOTAL_REVENUE,
        PREV_REVENUE, NEXT_REVENUE, REVENUE_GAP, LAST_CALCULATED
    ) VALUES (
        src.CUSTOMER_ID, src.REVENUE_RANK, src.QUARTILE, src.TOTAL_REVENUE,
        src.PREV_REVENUE, src.NEXT_REVENUE, src.REVENUE_GAP, SYSDATE
    );

    -- Step 2: Product trending using LEAD/LAG for period-over-period
    INSERT INTO SALES.PRODUCT_TRENDS (
        PRODUCT_ID, PERIOD, PERIOD_REVENUE, PREV_PERIOD_REVENUE,
        NEXT_PERIOD_REVENUE, TREND_DIRECTION
    )
    SELECT
        PRODUCT_ID,
        PERIOD,
        PERIOD_REVENUE,
        LAG(PERIOD_REVENUE, 1) OVER (PARTITION BY PRODUCT_ID ORDER BY PERIOD) AS PREV_PERIOD_REVENUE,
        LEAD(PERIOD_REVENUE, 1) OVER (PARTITION BY PRODUCT_ID ORDER BY PERIOD) AS NEXT_PERIOD_REVENUE,
        DECODE(
            SIGN(PERIOD_REVENUE - LAG(PERIOD_REVENUE, 1, 0) OVER (PARTITION BY PRODUCT_ID ORDER BY PERIOD)),
            1, 'UP',
            -1, 'DOWN',
            'FLAT'
        ) AS TREND_DIRECTION
    FROM (
        SELECT
            PRODUCT_ID,
            TO_CHAR(ORDER_DATE, 'YYYY-MM') AS PERIOD,
            SUM(QUANTITY * UNIT_PRICE) AS PERIOD_REVENUE
        FROM SALES.ORDERS
        WHERE ORDER_DATE >= ADD_MONTHS(SYSDATE, -24)
        GROUP BY PRODUCT_ID, TO_CHAR(ORDER_DATE, 'YYYY-MM')
    );

    DBMS_OUTPUT.PUT_LINE('Rankings calculated at ' || TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'));

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
        RAISE;
END SP_CALC_RANKINGS;
/
